### ISSUE TITLE
Button Function: Start

### ISSUE THREAD

**Issue by hfambia** [hfambia/ece115.2-exam#1]
Make start button functional

**Comment by naizarpiang** [comment]
try mo daw to,..

def Start(self):                                          
        if not self._running:            
            self._start = time.time() - self._elapsedtime
            self._running = 1

**Comment by hfambia** [comment]
nag add ako ng function na mag update ng time automatically, I add ko yun sa function mo 👍

**Comment by naizarpiang** [comment]
ahhh kulang pala ng function for update, sigee thank youuuu

**Comment by hfambia** [comment]
Oks na, ga work na, thank you!
