### ISSUE TITLE
Button Function: Stop

### ISSUE THREAD

**Issue by hfambia** [hfambia/ece115.2-exam#2]
Make stop button functional

**Comment by hfambia** [comment]
Lantawa tung code ni Kim sa Reset, I modify lang to, I think mag work?

**Comment by FloresMichaelRey** [comment]
Ok sige2 wait

**Comment by FloresMichaelRey** [comment]
Kani daw oh paki check 

def Stop(self):                                    
        if self._running:
            self.after_cancel(self._timer)            
            self._elapsedtime = time.time() - self._start    
            self._setTime(self._elapsedtime)
            self._running = 0

**Comment by hfambia** [comment]
Ok na, paki add lang sa code haa

**Comment by FloresMichaelRey** [comment]
Done na. Na add na nako
