### ISSUE TITLE
Button Function: Reset

### ISSUE THREAD

**Issue by hfambia** [hfambia/ece115.2-exam#3]
Make reset button functional

**Comment by Kim-Suarez** [comment]
Here

def Reset(self):                                 
        self._start = time.time()         
        self._elapsedtime = 0.0
        self.laps = []   
        self._setTime(self._elapsedtime)
        self.after_cancel(self._timer)            
        self._elapsedtime = time.time() - self._start    
        self._running = 0

**Comment by hfambia** [comment]
Mag work rin ang latter half sa code para sa Stop code, nice 👍
