### ISSUE TITLE
Button Function: Lap

### ISSUE THREAD

**Issue by hfambia** [hfambia/ece115.2-exam#4]
Make lap button functional

**Comment by villanuevacristymae** [comment]
def Lap(self):
        tempo = self._elapsedtime - self.prevLapHolder
        if self._running:
            self.laps.append(self._setLapTime(tempo))
            self.m.insert(END, self.laps[-1])
            self.m.yview_moveto(1)
            self.prevLapHolder = self._elapsedtime

**Comment by hfambia** [comment]
Oks na na optimize nanako ug ga work na, thank youuu
