### ISSUE TITLE
Create Main Timer and Lap times

### ISSUE THREAD

**Issue by hfambia** [hfambia/ece115.2-exam#6]

**Comment by hfambia** [comment]
Research mo about sa Scrollbar kay di pud ko kabalo hahaha

**Comment by naizarpiang** [comment]
ok waiysttt may na researchg ako

You can create simple a scrollbar as follows:
1. from tkinter import * screen = Tk()
2. screen. geometry('400x400') scrollbar_tk = Scrollbar(screen)
3. scrollbar_tk. pack(side=RIGHT, fill=Y. listbox_tk = Listbox(screen, yscrollcommand=scrollbar_tk.set)
4.  scrollbar_tk. config(command=listbox_tk.yview. mainloop()

**Comment by hfambia** [comment]
`class StopWatch(Frame):                                                           
    def __init__(self, parent=None, **kw):        
        Frame.__init__(self, parent, kw)
        self._elapsedtime = 0.0
        self.timestr = StringVar()
        self.makeWidgets()
        
    def makeWidgets(self):                         
        self.e = Entry(self)
        l = Label(self, textvariable=self.timestr)
        self._setTime(self._elapsedtime)
        l.pack(fill=X, expand=NO, pady=4, padx=2)
        l2 = Label(self, text='Laps')
        l2.pack(fill=X, expand=NO, pady=4, padx=90)
        scrollbar = Scrollbar(self, orient=VERTICAL)
        self.m = Listbox(self,selectmode=EXTENDED, height = 5, yscrollcommand=scrollbar.set)
        self.m.pack(side=LEFT, fill=BOTH, expand=1, pady=5, padx=2)
        scrollbar.config(command=self.m.yview)
        scrollbar.pack(side=RIGHT, fill=Y)
        
    def _setTime(self, elap):
        minutes = int(elap/60)
        seconds = int(elap - minutes*60.0)
        hseconds = int((elap - minutes*60.0 - seconds)*100)                
        self.timestr.set('%02d:%02d:%02d' % (minutes, seconds, hseconds))`

Solved na pero if naa pa mo suggestion, add ra mo ha

**Comment by hfambia** [comment]
Small addition pero nag add kog Text above sa timer ug gi fix nako gamay ang spacing 👍

**Comment by hfambia** [comment]
Kung napamoy maisip or suggestion I add sa program paki tell here
